#!/bin/bash
# alien added permissions fixup code
chown 'bin:bin' '/usr/sbin/drm_setup'
chown 'bin:bin' '/usr/sbin/rsct/bin/IBM.DRMd'
chown 'bin:bin' '/usr/sbin/rsct/cfg/rmdefs/IBM.DRM.cdef'
chown 'bin:bin' '/usr/sbin/rsct/cfg/rmdefs/IBM.DRM.mdef'
chown 'bin:bin' '/usr/sbin/rsct/trctmplts/IDRD.tpl'
chown 'bin:bin' '/usr/share/locale/C/LC_MESSAGES/IBM.DRM.cat'

# Post-Install
if [ -e /usr/sbin/rsct/bin/rmcctrl ]; then
	if [ "$1" = 1 ]; then
		if [[ "$(stat -c %d:%i /)" = "$(stat -c %d:%i /proc/1/root/.)" ]]; then
			/usr/sbin/drm_setup
		else
			echo "Please run /usr/sbin/drm_setup to configure DynamicRM"
		fi
	fi

	if [[ "$1" > 0 && "$(stat -c %d:%i /)" = "$(stat -c %d:%i /proc/1/root/.)" ]]; then
		/usr/sbin/rsct/bin/rmcctrl -A
		/usr/sbin/rsct/bin/rmcctrl -p
	fi
fi